
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class JFrame_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Principal.class.getName());

    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ghost1 = new javax.swing.JButton();
        jButton_ghost2 = new javax.swing.JButton();
        jButton_fruta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_ghost1.setText("1");
        jButton_ghost1.setFocusable(false);

        jButton_ghost2.setText("2");
        jButton_ghost2.setFocusable(false);
        jButton_ghost2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ghost2ActionPerformed(evt);
            }
        });

        jButton_fruta.setText("@");
        jButton_fruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_frutaActionPerformed(evt);
            }
        });
        jButton_fruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_frutaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ghost2)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton_ghost1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton_fruta)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton_ghost1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton_fruta)
                .addGap(43, 43, 43)
                .addComponent(jButton_ghost2)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ghost2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ghost2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ghost2ActionPerformed

    private void jButton_frutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_frutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_frutaActionPerformed

    private void jButton_frutaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_frutaKeyPressed
        switch (evt.getKeyCode()) {
            case 38:
                System.out.println("cima");
                Movimento.cima(jButton_ghost1);
                break;
            case 40:
                System.out.println("baixo");
                Movimento.baixo(jButton_ghost1, this);
                break;
            case 37:
                System.out.println("esquerda");
                Movimento.esquerda(jButton_ghost1);
                break;
            case 39:
                System.out.println("direita");
                Movimento.direita(jButton_ghost1, this);
                break;
                
            case 87:
                System.out.println("cima");
                Movimento.cima(jButton_ghost2);
                break;
            case 83:
                System.out.println("baixo");
                Movimento.baixo(jButton_ghost2, this);
                break;
            case 65:
                System.out.println("esquerda");
                Movimento.esquerda(jButton_ghost2);
                break;
            case 68:
                System.out.println("direita");
                Movimento.direita(jButton_ghost2, this);
                break;
                
            default:
                throw new AssertionError();
        }
        
        if (jButton_ghost1.getBounds().intersects(jButton_fruta.getBounds())) {
            Movimento.sorteiaPosicao(jButton_fruta, this);
        }
        if (jButton_ghost2.getBounds().intersects(jButton_fruta.getBounds())) {
            Movimento.sorteiaPosicao(jButton_fruta, this);
        }
    }//GEN-LAST:event_jButton_frutaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_fruta;
    private javax.swing.JButton jButton_ghost1;
    private javax.swing.JButton jButton_ghost2;
    // End of variables declaration//GEN-END:variables
}
