
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Miguel
 */
public class JFrame_FruitChase extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_FruitChase.class.getName());
    public Set<Integer> pressed = new HashSet<>();
    public int pontuacaoJogador1 = 0;
    public int pontuacaoJogador2 = 0;

    /**
     * Creates new form FruitChase
     */
    public JFrame_FruitChase() {
        initComponents();
        getContentPane().setLayout(null);
        
        //Thread que fica verificando as teclas pressionadas e soltadas a cada 40 ms
        new Thread() {
            public void run() {
                while (true) {
                    try {
                        verificaTeclas();
                        try {
                            sleep(40);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(JFrame_FruitChase.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (Exception e) {
                        System.out.println("Erro na Thread: " + e.getMessage());
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton_Ghost1 = new javax.swing.JButton();
        jButton_Ghost2 = new javax.swing.JButton();
        jButton_Fruta = new javax.swing.JButton();
        jLabel_pontuacaoJogador1 = new javax.swing.JLabel();
        jLabel_pontuacaoJogador2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Ghost1.setText("1");
        jButton_Ghost1.setFocusable(false);
        jButton_Ghost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ghost1ActionPerformed(evt);
            }
        });

        jButton_Ghost2.setText("2");
        jButton_Ghost2.setFocusable(false);
        jButton_Ghost2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ghost2ActionPerformed(evt);
            }
        });

        jButton_Fruta.setText("@");
        jButton_Fruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FrutaActionPerformed(evt);
            }
        });
        jButton_Fruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_FrutaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_FrutaKeyReleased(evt);
            }
        });

        jLabel_pontuacaoJogador1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_pontuacaoJogador1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pontuacaoJogador1.setFocusable(false);
        jLabel_pontuacaoJogador1.setOpaque(true);

        jLabel_pontuacaoJogador2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_pontuacaoJogador2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pontuacaoJogador2.setFocusable(false);
        jLabel_pontuacaoJogador2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Fruta)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Ghost2)
                                .addGap(54, 54, 54))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Ghost1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel_pontuacaoJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_pontuacaoJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_pontuacaoJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_pontuacaoJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Ghost1)
                .addGap(37, 37, 37)
                .addComponent(jButton_Fruta)
                .addGap(2, 2, 2)
                .addComponent(jButton_Ghost2)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Ghost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ghost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Ghost1ActionPerformed

    private void jButton_Ghost2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ghost2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Ghost2ActionPerformed

    private void jButton_FrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_FrutaActionPerformed
    /***
     * Pega o codigo da tecla pressionada e adiciona em um HashSet
     * @param evt
     */
    private void jButton_FrutaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_FrutaKeyPressed
        //Utiliza synchronized para evitar que duas ou mais threads 
        //modifiquem o HashSet ao mesmo tempo
        synchronized (JFrame_FruitChase.this) {
            pressed.add(evt.getKeyCode());
        }
    }//GEN-LAST:event_jButton_FrutaKeyPressed
    /***
     * Pega o codigo da tecla soltada e adiciona em um HashSet
     * @param evt
     */
    private void jButton_FrutaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_FrutaKeyReleased
        //Utiliza synchronized para evitar que duas ou mais threads 
        //modifiquem o HashSet ao mesmo tempo
        synchronized (JFrame_FruitChase.this) {
            pressed.remove(evt.getKeyCode());
        }
    }//GEN-LAST:event_jButton_FrutaKeyReleased
    /***
     * verifica quais teclas foram pressionadas e faz o movimento para cada uma
     */
    public void verificaTeclas() {
            for(Integer tecla : pressed){
                switch (tecla) {
                    case 38: Movimento.cima(jButton_Ghost1); break;
                    case 40: Movimento.baixo(jButton_Ghost1, this); break;
                    case 37: Movimento.esquerda(jButton_Ghost1); break;
                    case 39: Movimento.direita(jButton_Ghost1, this); break;
                    case 87: Movimento.cima(jButton_Ghost2); break;
                    case 83: Movimento.baixo(jButton_Ghost2, this); break;
                    case 65: Movimento.esquerda(jButton_Ghost2); break;
                    case 68: Movimento.direita(jButton_Ghost2, this); break;
                }

            //Se o jogador 1 pegou a frutinha
            if (Util.pegou(jButton_Fruta, jButton_Ghost1)) {
                jButton_Fruta = Util.sorteiaPosicao(jButton_Fruta, JFrame_FruitChase.this, jButton_Ghost1, jButton_Ghost2);
                pontuacaoJogador1++;
                jLabel_pontuacaoJogador1.setText("Jogador1 : " + pontuacaoJogador1);
            }
            
            //Se o jogador 2 pegou a frutinha
            if (Util.pegou(jButton_Fruta, jButton_Ghost2)) {
                jButton_Fruta = Util.sorteiaPosicao(jButton_Fruta, JFrame_FruitChase.this, jButton_Ghost1, jButton_Ghost2);
                pontuacaoJogador2++;
                jLabel_pontuacaoJogador2.setText("Jogador2: " + pontuacaoJogador2);
            }
            
            //Se o jogador 1 ganhou (Conseguiu 10 pontos)
            if(pontuacaoJogador1 == 10){
                // LIMPA as teclas ANTES de mostrar o diálogo
                synchronized (this) {
                    pressed.clear();
                }
                
                int resposta = JOptionPane.showConfirmDialog(this, 
                    "Jogador 1 venceu!\nDeseja jogar novamente?", 
                    "Fim de Jogo", 
                    JOptionPane.YES_NO_OPTION);

                if(resposta == JOptionPane.YES_OPTION){
                    reiniciarJogo();
                } else {
                    // Fecha o jogo
                    System.exit(0); 
                }
            //Se o jogador 2 ganhou (Conseguiu 10 pontos)
            } else if (pontuacaoJogador2 == 10){
                // LIMPA as teclas ANTES de mostrar o diálogo
                synchronized (this) {
                    pressed.clear();
                }
                
                int resposta = JOptionPane.showConfirmDialog(this, 
                    "Jogador 2 venceu!\nDeseja jogar novamente?", 
                    "Fim de Jogo", 
                    JOptionPane.YES_NO_OPTION);

                if(resposta == JOptionPane.YES_OPTION){
                    reiniciarJogo();
                } else {
                    System.exit(0); // Fecha o jogo
                }
            } 
        }
    }
    
    private void reiniciarJogo() {
        // Zera as pontuações
        pontuacaoJogador1 = 0;
        pontuacaoJogador2 = 0;

        // Atualiza os textos na tela
        jLabel_pontuacaoJogador1.setText("Jogador1 : " + pontuacaoJogador1);
        jLabel_pontuacaoJogador2.setText("Jogador2 : " + pontuacaoJogador2);

        // REPOSICIONA MANUALMENTE nas posições iniciais
        jButton_Ghost1.setBounds(100, 200, jButton_Ghost1.getWidth(), jButton_Ghost1.getHeight());  // Posição inicial jogador 1
        jButton_Ghost2.setBounds(200, 200, jButton_Ghost2.getWidth(), jButton_Ghost2.getHeight()); // Posição inicial jogador 2
        
        // Sorteia nova posição só para a frutinha
        jButton_Fruta = Util.sorteiaPosicao(jButton_Fruta, this, jButton_Ghost1, jButton_Ghost2);
        
        // Garante o foco na frutinha para capturar teclas
        jButton_Fruta.requestFocus();

        // Força repaint da tela
        repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_FruitChase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_FruitChase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_FruitChase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_FruitChase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_FruitChase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Fruta;
    private javax.swing.JButton jButton_Ghost1;
    private javax.swing.JButton jButton_Ghost2;
    private javax.swing.JLabel jLabel_pontuacaoJogador1;
    private javax.swing.JLabel jLabel_pontuacaoJogador2;
    // End of variables declaration//GEN-END:variables
}
